spring:
  application:
    name: cloud-zuul
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 自定义指定微服务的访问路径
zuul:
  routes:
    cloud-provider: /user/hello/**